// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DKQGqJc9Du3RTrtzsP3X2NC8KUg7XY4',
    appId: '1:40512577014:web:c844f689e0a0cee4423bd7',
    messagingSenderId: '40512577014',
    projectId: 'bharathienterprises-3f1f3',
    authDomain: 'bharathienterprises-3f1f3.firebaseapp.com',
    storageBucket: 'bharathienterprises-3f1f3.firebasestorage.app',
    measurementId: 'G-61SQMK0TQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMGLNKBZPJPdbmzGLOgFt70hTV6lM5a0',
    appId: '1:40512577014:android:071c303151848b6d423bd7',
    messagingSenderId: '40512577014',
    projectId: 'bharathienterprises-3f1f3',
    storageBucket: 'bharathienterprises-3f1f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0W0qrpyqWuTZZNGjRWSg6wykTSl35jJ4',
    appId: '1:40512577014:ios:f2f203e4693df45c423bd7',
    messagingSenderId: '40512577014',
    projectId: 'bharathienterprises-3f1f3',
    storageBucket: 'bharathienterprises-3f1f3.firebasestorage.app',
    iosBundleId: 'com.example.bhargaviOilMasala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0W0qrpyqWuTZZNGjRWSg6wykTSl35jJ4',
    appId: '1:40512577014:ios:f2f203e4693df45c423bd7',
    messagingSenderId: '40512577014',
    projectId: 'bharathienterprises-3f1f3',
    storageBucket: 'bharathienterprises-3f1f3.firebasestorage.app',
    iosBundleId: 'com.example.bhargaviOilMasala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8DKQGqJc9Du3RTrtzsP3X2NC8KUg7XY4',
    appId: '1:40512577014:web:d052bd2fc508c5f3423bd7',
    messagingSenderId: '40512577014',
    projectId: 'bharathienterprises-3f1f3',
    authDomain: 'bharathienterprises-3f1f3.firebaseapp.com',
    storageBucket: 'bharathienterprises-3f1f3.firebasestorage.app',
    measurementId: 'G-YBHL4VSW27',
  );
}
